### ISSUE TITLE
Getting errors when using

### ISSUE THREAD

**Issue by Cannonb4ll** [timothyasp/nova-color-field#1]
Does not seem to work for me, using laravel nova 1.0.6.

After installing and using the Color field I get these errors:

`nova-api/scripts/color 500 (Internal Server Error)`
`nova-api/styles/color 500 (Internal Server Error)`

**Comment by jorgv** [comment]
In the Nova resource include the class as:

`use Timothyasp\Color\Color;`

**Comment by Cannonb4ll** [comment]
This is solved as the publisher forgot to add the dist folder inside the package. Thank you!
