### ISSUE TITLE
Empty value selects black from palette

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [timothyasp/nova-color-field#15]
If the field is initialised with (or edited to) an empty string, and I am using the `compact` component, for some reason the `#000000` (eg the black) swatch appears to be selected?

Notice in this image all 3 color fields are empty, and yet for some reason the black swatch is selected:
<img width="539" alt="Screen Shot 2021-04-17 at 1 20 29 am" src="https://user-images.githubusercontent.com/41524/115050654-21817e00-9f1b-11eb-9453-48bfe927b313.png">

Is this an issue with `nova-color-field` or the underlying `vue-color` component?

**Comment by timothyasp** [comment]
This should be fixed with v2.0.1

**Comment by whitespacecode** [comment]
Empty value still results the color field picking #ffffff
Also i have not found a way to 'empty' the color field.
