### ISSUE TITLE
onClick appearance

### ISSUE THREAD

**Issue by vwasteels** [timothyasp/nova-color-field#9]
hello!

I don't know if it's designed like this by default, but my colorpicker is always showing, is there a way to make it appear on click only ?

thank you :)

**Comment by timothyasp** [comment]
Some of the other palettes from vue-color might have this feature, but I don't remember.

**Comment by milewski** [comment]
Made a PR for it.. by default it keeps the same behavior as currently, however if you add `->autoHidePicker()` it shows/hides the picker based on input focus or click
